services:
  word-service:
    build: ./word-service
    container_name: WordService
    environment:
      - WORD_SERVICE_PORT=${WORD_SERVICE_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "${WORD_SERVICE_PORT}:${WORD_SERVICE_PORT}"
    networks:
      - app-network

  gateway-service:
    build: ./api-gateway
    container_name: ApiGateway
    environment:
      - GATEWAY_SERVICE_PORT=${GATEWAY_SERVICE_PORT}
      - JWT_SECURITY_KEY=${APPLICATION_SECURITY_JWT_SECRET_KEY}
      - JWT_EXPIRATION_TIME=${APPLICATION_SECURITY_JWT_EXPIRATION}
    ports:
      - "${GATEWAY_SERVICE_PORT}:${GATEWAY_SERVICE_PORT}"
    depends_on:
      - word-service
      - identity-service
    networks:
      - app-network

  identity-service:
    build: ./identity-service
    container_name: IdentityService
    environment:
      - IDENTITY_SERVICE_PORT=${IDENTITY_SERVICE_PORT}
      - JWT_SECURITY_KEY=${APPLICATION_SECURITY_JWT_SECRET_KEY}
      - JWT_EXPIRATION_TIME=${APPLICATION_SECURITY_JWT_EXPIRATION}
      - JWT_REFRESH_EXPIRATION_TIME=${APPLICATION_SECURITY_JWT_REFRESH_EXPIRATION_TIME}
    ports:
      - "${IDENTITY_SERVICE_PORT}:${IDENTITY_SERVICE_PORT}"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge