server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: word-service
            uri: http://word-service:777
            predicates:
              - Path=/graphql/wordService
            filters:
              - SetPath=/graphql
          - id: identity-service
            uri: http://identity-service:7771
            predicates:
              Path=/graphql/IdentityService
            filters:
              SetPath=/graphql