package pl.cinkus.IdentityService.exception;

public enum ErrorCode {
    EMAIL_OR_NICKNAME_ALREADY_TAKEN,
    USER_NOT_FOUND,
    INVALID_PASSWORD,
    INTERNAL_SERVER_ERROR,
    VALIDATION_ERROR,
    INVALID_REFRESH_TOKEN,
    REFRESH_TOKEN_EXPIRED
}