enum UserRole {
    ADMIN
    USER
    TEACHER
}

input NewUserData {
    name: String!
    surname: String!
    nickName: String!
    role: UserRole!
    email: String!
    password: String!
}

input UserLoginData {
    email: String!
    password: String!
}

type LoginResult {
    token: String!
    refreshToken: String!
}

type Query {
    getAllUsers: [String]
}

type Mutation {
    register(userData: NewUserData): Boolean
    login(userLoginData: UserLoginData): LoginResult
    refresh(refreshToken: String!): LoginResult
}